version: '3'
services:
  master:
    image: ${IMAGE_NAME}:${TAG}
    container_name: master
    hostname: master
    ports:
      - "${EXPOSE_MASTER_PORT}:5432"
    environment:
      - GREENPLUM_DEPLOYMENT=master
      - GREENPLUM_GPPERFMON_ENABLE=true
      - GREENPLUM_DISKQUOTA_ENABLE=true
      - GREENPLUM_WALG_ENABLE=true
      - GREENPLUM_PXF_ENABLE=true
      - GREENPLUM_PASSWORD_FILE=/run/secrets/gpdb_password
      - GREENPLUM_GPMON_PASSWORD_FILE=/run/secrets/gpmon_password
    secrets:
      - gpdb_password
      - gpmon_password
    volumes:
      - ../docker-compose/conf/${CONFIG_FOLDER}/gpinitsystem_config_no_mirrors:/tmp/gpinitsystem_config
      - ../docker-compose/conf/hostfile_gpinitsystem:/tmp/hostfile_gpinitsystem
      - ../docker-compose/conf/ssh/id_rsa:/home/gpadmin/.ssh/id_rsa
      - ../docker-compose/conf/ssh/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub
      - ./wal-g/conf/${CONFIG_FOLDER}/wal-g.yaml:/tmp/wal-g.yaml
      - ./wal-g/init_scripts/wal-g_init.sh:/docker-entrypoint-initdb.d/wal-g_init.sh
      - ./wal-g/init_scripts/table_init.sql:/docker-entrypoint-initdb.d/table_init.sql
    depends_on:
      - segment1
      - segment2
    networks:
      - greenplum

  segment1:
    image: ${IMAGE_NAME}:${TAG}
    container_name: segment1
    hostname: segment1
    command: /start_gpdb.sh "00:primary" "01:primary"
    environment:
      - GREENPLUM_DEPLOYMENT=segment
    volumes:
      - ../docker-compose/conf/ssh/authorized_keys:/tmp/authorized_keys
      - ./wal-g/conf/${CONFIG_FOLDER}/wal-g.yaml:/tmp/wal-g.yaml
    stop_grace_period: 60s
    networks:
      - greenplum

  segment2:
    image: ${IMAGE_NAME}:${TAG}
    container_name: segment2
    hostname: segment2
    command: /start_gpdb.sh "00:primary" "01:primary"
    environment:
      - GREENPLUM_DEPLOYMENT=segment
    volumes:
      - ../docker-compose/conf/ssh/authorized_keys:/tmp/authorized_keys
      - ./wal-g/conf/${CONFIG_FOLDER}/wal-g.yaml:/tmp/wal-g.yaml
    stop_grace_period: 60s
    networks:
      - greenplum

networks:
  greenplum:

secrets:
  gpdb_password:
    file: ../docker-compose/secrets/gpdb_password
  gpmon_password:
    file: ../docker-compose/secrets/gpmon_password