name: build-gpdb6

on: [push, pull_request]

jobs:
  detect_changes:
    runs-on: ubuntu-22.04
    outputs:
      project_changed: ${{ steps.changed-files.outputs.project_any_changed }}
      common_changed: ${{ steps.changed-files.outputs.common_any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@7dee1b0c1557f278e5c7dc244927139d78c0e22a
        with:
          files_yaml: |
            project:
              - 'docker/greenplum/**/6/**'
            common:
              - 'docker/files/entrypoint.sh'
              - 'docker/files/start_gpdb.sh'
              - '.github/workflows/build-gpdb6.yml'

  build_image:
    needs: [detect_changes]
    if: |
      needs.detect_changes.outputs.project_changed == 'true' ||
      needs.detect_changes.outputs.common_changed == 'true' ||
      github.ref == 'refs/heads/master' ||
      startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    strategy:
      matrix:
        greenplum_version: ["6.27.1"]
        os_version: ["ubuntu22.04", "oraclelinux8"]
        platform: ["linux/amd64", "linux/arm64"]
    steps:
    - uses: actions/checkout@v4

    - name: Get repo tag
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      id: vars
      run: |
        echo "repo_tag=$(echo ${GITHUB_REF} | cut -d'/' -f3)" >> $GITHUB_OUTPUT
    
    - name: Set Architecture
      run: |
        if [ "${{ matrix.platform }}" = "linux/amd64" ]; then
          echo "ARCH=amd64" >> $GITHUB_ENV
        else
          echo "ARCH=arm64" >> $GITHUB_ENV
        fi

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKEHUB_USER }}
        password: ${{ secrets.DOCKEHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GUTHUB_CR_PAT }}

    - name: Build greenplum image (Test Build)
      run: |
        docker buildx build \
          -f docker/greenplum/${OS_TAG}/6/Dockerfile \
          --platform ${{ matrix.platform }} \
          --build-arg GPDB_VERSION=${TAG} \
          --build-arg REPO_BUILD_TAG=${REPO_TAG} \
          -t greenplum:${TAG}-${ARCH} .
      env: 
        TAG: ${{ matrix.greenplum_version }}
        OS_TAG: ${{ matrix.os_version }}
        REPO_TAG: ${{ steps.vars.outputs.repo_tag }}

    - name: Build and push platform specific images
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        GHCR_BASE="ghcr.io/${GITHUB_USER}/greenplum"
        DH_BASE="${DOCKERHUB_USER}/greenplum"

        docker buildx build --push \
            -f docker/greenplum/${OS_TAG}/6/Dockerfile \
            --platform ${{ matrix.platform }} \
            --build-arg GPDB_VERSION=${TAG} \
            --build-arg REPO_BUILD_TAG=${REPO_TAG} \
            -t ${GHCR_BASE}:${TAG}-${OS_TAG}-${ARCH} \
            -t ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-${ARCH} \
            -t ${DH_BASE}:${TAG}-${OS_TAG}-${ARCH} \
            -t ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-${ARCH} .
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_PKG: ${{ secrets.GUTHUB_CR_PAT }}
        DOCKERHUB_USER: ${{ secrets.DOCKEHUB_USER }}
        DOCKERHUB_PKG: ${{ secrets.DOCKEHUB_TOKEN }}
        TAG: ${{ matrix.greenplum_version }}
        OS_TAG: ${{ matrix.os_version }}
        REPO_TAG: ${{ steps.vars.outputs.repo_tag }}

  merge_manifests:
    runs-on: ubuntu-22.04
    needs: build_image
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        greenplum_version: ["6.27.1"]
        os_version: ["ubuntu22.04", "oraclelinux8"]
    steps:
      - name: Get repo tag
        id: vars
        run: |
          echo "repo_tag=$(echo ${GITHUB_REF} | cut -d'/' -f3)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKEHUB_USER }}
          password: ${{ secrets.DOCKEHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GUTHUB_CR_PAT }}

      - name: Create and push manifest lists
        run: |
          GHCR_BASE="ghcr.io/${GITHUB_USER}/greenplum"
          DH_BASE="${DOCKERHUB_USER}/greenplum"
          
          docker buildx imagetools create -t ${GHCR_BASE}:${TAG}-${OS_TAG} \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-amd64 \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-arm64
            
          docker buildx imagetools create -t ${DH_BASE}:${TAG}-${OS_TAG} \
            ${DH_BASE}:${TAG}-${OS_TAG}-amd64 \
            ${DH_BASE}:${TAG}-${OS_TAG}-arm64

          docker buildx imagetools create -t ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG} \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-amd64 \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-arm64
            
          docker buildx imagetools create -t ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG} \
            ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-amd64 \
            ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-arm64

        env:
          GITHUB_USER: ${{ github.actor }}
          DOCKERHUB_USER: ${{ secrets.DOCKEHUB_USER }}
          TAG: ${{ matrix.greenplum_version }}
          OS_TAG: ${{ matrix.os_version }}
          REPO_TAG: ${{ steps.vars.outputs.repo_tag }}

      - name: Create and push default manifest lists (ubuntu22.04 only)
        if: matrix.os_version == 'ubuntu22.04'
        run: |
          GHCR_BASE="ghcr.io/${GITHUB_USER}/greenplum"
          DH_BASE="${DOCKERHUB_USER}/greenplum"

          # 1. Manifest for ${TAG}
          docker buildx imagetools create -t ${GHCR_BASE}:${TAG} \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-amd64 \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-arm64
            
          docker buildx imagetools create -t ${DH_BASE}:${TAG} \
            ${DH_BASE}:${TAG}-${OS_TAG}-amd64 \
            ${DH_BASE}:${TAG}-${OS_TAG}-arm64

          # 2. Manifest for ${TAG}-${REPO_TAG}
          docker buildx imagetools create -t ${GHCR_BASE}:${TAG}-${REPO_TAG} \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-amd64 \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-arm64
            
          docker buildx imagetools create -t ${DH_BASE}:${TAG}-${REPO_TAG} \
            ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-amd64 \
            ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-arm64
        env:
          GITHUB_USER: ${{ github.actor }}
          DOCKERHUB_USER: ${{ secrets.DOCKEHUB_USER }}
          TAG: ${{ matrix.greenplum_version }}
          OS_TAG: ${{ matrix.os_version }}
          REPO_TAG: ${{ steps.vars.outputs.repo_tag }}