name: build-greengage6

on: [push, pull_request]

jobs:
  detect_changes:
    runs-on: ubuntu-22.04
    outputs:
      project_changed: ${{ steps.changed-files.outputs.project_any_changed }}
      common_changed: ${{ steps.changed-files.outputs.common_any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96
        with:
          files_yaml: |
            project:
              - 'docker/greengage/**/6/**'
            common:
              - 'docker/files/entrypoint.sh'
              - 'docker/files/start_gpdb.sh'
              - '.github/workflows/build-greengage6.yml'

      - name: Log build trigger reason
        run: |
          if [[ "${{ steps.changed-files.outputs.project_any_changed }}" == "true" || \
               "${{ steps.changed-files.outputs.common_any_changed }}" == "true" || \
               "${{ github.ref }}" == "refs/heads/master" || \
               "${{ github.ref }}" == refs/tags/* ]]; then
            echo "build_image will run"
          else
            echo "build_image will be skipped"
          fi

  build_image:
    needs: [detect_changes]
    if: |
      needs.detect_changes.outputs.project_changed == 'true' ||
      needs.detect_changes.outputs.common_changed == 'true' ||
      github.ref == 'refs/heads/master' ||
      startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    strategy:
      matrix:
        greengage_version: ["6.31.0"]
        os_version: ["ubuntu22.04", "oraclelinux8"]
        platform: ["linux/amd64", "linux/arm64"]
    steps:
    - uses: actions/checkout@v7

    - name: Get repo tag
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      id: vars
      run: |
        echo "repo_tag=$(echo ${GITHUB_REF} | cut -d'/' -f3)" >> $GITHUB_OUTPUT
    
    - name: Set Architecture
      run: |
        if [ "${{ matrix.platform }}" = "linux/amd64" ]; then
          echo "ARCH=amd64" >> $GITHUB_ENV
        else
          echo "ARCH=arm64" >> $GITHUB_ENV
        fi

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKEHUB_USER }}
        password: ${{ secrets.DOCKEHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GUTHUB_CR_PAT }}

    - name: Build greengage image (Test Build)
      run: |
        docker buildx build \
          -f docker/greengage/${OS_TAG}/6/Dockerfile \
          --platform ${{ matrix.platform }} \
          --build-arg GPDB_VERSION=${TAG} \
          --build-arg REPO_BUILD_TAG=${REPO_TAG} \
          -t greengage:${TAG}-${ARCH} .
      env: 
        TAG: ${{ matrix.greengage_version }}
        OS_TAG: ${{ matrix.os_version }}
        REPO_TAG: ${{ steps.vars.outputs.repo_tag }}

    - name: Build and push platform specific images
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        GHCR_BASE="ghcr.io/${GITHUB_USER}/greengage"
        DH_BASE="${DOCKERHUB_USER}/greengage"

        docker buildx build --push \
            -f docker/greengage/${OS_TAG}/6/Dockerfile \
            --platform ${{ matrix.platform }} \
            --build-arg GPDB_VERSION=${TAG} \
            --build-arg REPO_BUILD_TAG=${REPO_TAG} \
            -t ${GHCR_BASE}:${TAG}-${OS_TAG}-${ARCH} \
            -t ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-${ARCH} \
            -t ${DH_BASE}:${TAG}-${OS_TAG}-${ARCH} \
            -t ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-${ARCH} .
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_PKG: ${{ secrets.GUTHUB_CR_PAT }}
        DOCKERHUB_USER: ${{ secrets.DOCKEHUB_USER }}
        DOCKERHUB_PKG: ${{ secrets.DOCKEHUB_TOKEN }}
        TAG: ${{ matrix.greengage_version }}
        OS_TAG: ${{ matrix.os_version }}
        REPO_TAG: ${{ steps.vars.outputs.repo_tag }}

  merge_manifests:
    runs-on: ubuntu-22.04
    needs: build_image
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        greengage_version: ["6.31.0"]
        os_version: ["ubuntu22.04", "oraclelinux8"]
    steps:
      - name: Get repo tag
        id: vars
        run: |
          echo "repo_tag=$(echo ${GITHUB_REF} | cut -d'/' -f3)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKEHUB_USER }}
          password: ${{ secrets.DOCKEHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GUTHUB_CR_PAT }}

      - name: Create and push manifest lists
        run: |
          GHCR_BASE="ghcr.io/${GITHUB_USER}/greengage"
          DH_BASE="${DOCKERHUB_USER}/greengage"
          
          docker buildx imagetools create -t ${GHCR_BASE}:${TAG}-${OS_TAG} \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-amd64 \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-arm64
            
          docker buildx imagetools create -t ${DH_BASE}:${TAG}-${OS_TAG} \
            ${DH_BASE}:${TAG}-${OS_TAG}-amd64 \
            ${DH_BASE}:${TAG}-${OS_TAG}-arm64

          docker buildx imagetools create -t ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG} \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-amd64 \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-arm64
            
          docker buildx imagetools create -t ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG} \
            ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-amd64 \
            ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-arm64

        env:
          GITHUB_USER: ${{ github.actor }}
          DOCKERHUB_USER: ${{ secrets.DOCKEHUB_USER }}
          TAG: ${{ matrix.greengage_version }}
          OS_TAG: ${{ matrix.os_version }}
          REPO_TAG: ${{ steps.vars.outputs.repo_tag }}

      - name: Create and push default manifest lists (ubuntu22.04 only)
        if: matrix.os_version == 'ubuntu22.04'
        run: |
          GHCR_BASE="ghcr.io/${GITHUB_USER}/greengage"
          DH_BASE="${DOCKERHUB_USER}/greengage"

          # 1. Manifest for ${TAG}
          docker buildx imagetools create -t ${GHCR_BASE}:${TAG} \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-amd64 \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-arm64
            
          docker buildx imagetools create -t ${DH_BASE}:${TAG} \
            ${DH_BASE}:${TAG}-${OS_TAG}-amd64 \
            ${DH_BASE}:${TAG}-${OS_TAG}-arm64

          # 2. Manifest for ${TAG}-${REPO_TAG}
          docker buildx imagetools create -t ${GHCR_BASE}:${TAG}-${REPO_TAG} \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-amd64 \
            ${GHCR_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-arm64
            
          docker buildx imagetools create -t ${DH_BASE}:${TAG}-${REPO_TAG} \
            ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-amd64 \
            ${DH_BASE}:${TAG}-${OS_TAG}-${REPO_TAG}-arm64
        env:
          GITHUB_USER: ${{ github.actor }}
          DOCKERHUB_USER: ${{ secrets.DOCKEHUB_USER }}
          TAG: ${{ matrix.greengage_version }}
          OS_TAG: ${{ matrix.os_version }}
          REPO_TAG: ${{ steps.vars.outputs.repo_tag }}
